version: '3.9'

services:
  app:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - MIGRATION_CONTEXTS=${MIGRATION_CONTEXTS}