version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=valuator_local_pass
      - POSTGRES_USER=valuator_local_user
      - POSTGRES_DB=valuator_local_db