spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath://db/changelog.yaml
    contexts: ${MIGRATION_CONTEXTS:prod}